version: "3"
services:
  app:
    build: ./
    image: ioa_kg
    container_name: ioa_demo_app
    ports:
      - 8450:8501
    volumes:
    #  - ./app/query_results:/app/query_results
      - ./app:/app
    command: ["streamlit", "run", "app.py", "--","--model_name","PaulD/IOA_ft_latest"]   
